### PR TITLE
Finalize local dev env setup

### PR DESCRIPTION
**Pull request by ronaldo-macapobre**
# Pull Request for JIRA Ticket: 10

## Issue ticket number and link  
https://jag.gov.bc.ca/jira/browse/JASPER-10

## Description

- Enable hot reloading for frontend code
- Add more info to README.md for local development.
- Changes made to the `vue.config.js` is necessary to avoid proxy error issues and does not affect the behavior of the old workflow where `web` artifact is used.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update    

## How Has This Been Tested?

- [x] Tested that hot reloading works in frontend code.
- [x] Tested that old workflow still works.

**Test Configuration**:
If applicable

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules   

## Documentation References  

N/A

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
Awesome job @ronaldo-macapobre!

A few recommendations.

1) Add the launch.json changes to the dev container configuration so it's always there for everyone by default.
2) Have the build always build all project containers.  This avoids having to make specific updates to the script.
3) Update the the `./manage` script to add a `debug` command that would start the set of containers for hot reloading and debugging, where the `start` command would start the compiled runtime set of containers.  This avoids having to edit the `./manage` script to access the different features.

**Comment by WadeBarnes** [comment]
Regarding the line ending issues.  You could add some additional lines to cover affected files to this file; https://github.com/bcgov/jasper/blob/master/.gitattributes

**Review by amlanc1 — APPROVED** [review]
lgtm

**Comment by WadeBarnes** [comment]
One item that might be worth noting in the documentation.  The dev container will fail to build if you are connected to the BC Government VPN when building/rebuilding.

**Comment by ronaldo-macapobre** [comment]
> Awesome job @ronaldo-macapobre!
> 
> A few recommendations.
> 
> 1. Add the launch.json changes to the dev container configuration so it's always there for everyone by default.
> 2. Have the build always build all project containers.  This avoids having to make specific updates to the script.
> 3. Update the the `./manage` script to add a `debug` command that would start the set of containers for hot reloading and debugging, where the `start` command would start the compiled runtime set of containers.  This avoids having to edit the `./manage` script to access the different features.

@WadeBarnes I tried suggestion **3.** but I encountered an error saying 0.0.0.0:8080 is already used when switching from `debug` and `start`. I tried simplifying the code so I added `build-debug` and `start-debug`. Let me know what you think.

**Review by WadeBarnes — COMMENTED** [review]
Hey @ronaldo-macapobre, Looking good!

I've added a few commits:
1) To further cleanup the `./manage` script and restore some functionality that was lost in the shuffle.
2) To relabel the images and routes from `scv` to `jasper`.
3) To update the development environment documentation based on the above changes.

Let me know what you think.  If you're happy with the updates we can merge the PR.

**Review by WadeBarnes — APPROVED** [review]
I think that's got it.  Great work @ronaldo-macapobre

**Pull request merged**
